version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: unbouncded_lcms
      POSTGRES_USER: unbouncded_lcms
      POSTGRES_DB: unbouncded_lcms
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  redis:
    image: redis:alpine
    restart: always
  web:
    build: .
    image: unbounded:lcms-latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - elasticsearch
      - redis
