source 'https://rubygems.org'

gem 'acts-as-taggable-on', '~> 3.5'
gem 'active_model_serializers', '~> 0.9.3'
gem 'activerecord-session_store', '~> 1.0'
gem 'aws-sdk-rails', '~> 1.0'
gem 'axlsx', '~> 2.1.0.pre'
gem 'bootstrap-sass', '~> 3.3.5.1'
gem 'carrierwave', '~> 0.10.0'
gem 'ckeditor'
gem 'closure_tree', '~> 6.0'
gem 'daemons', '~> 1.2', '>= 1.2.3'
gem 'devise', '~> 3.5.2', require: ['devise', 'devise/orm/active_record']
gem 'dotenv-rails', '~> 2.0.2', groups: [:development, :integration, :test]
gem 'edge', '~> 0.4.2', require: 'edge'
gem 'elasticsearch-dsl', '~> 0.1.1'
gem 'elasticsearch-model', '~> 0.1.7'
gem 'elasticsearch-persistence', '~> 0.1.7'
gem 'elasticsearch-rails', '~> 0.1.7'
gem 'fog', '~> 1.38'
gem 'font-awesome-sass', '~> 4.4.0'
gem 'foreman', '~> 0.78.0'
gem 'google-api-client', '~> 0.9'
gem 'googleauth', '~> 0.4'
gem 'i18n-js', '~> 2.1.2'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'js-routes', '~> 1.1.2'
gem 'nested_form'
gem 'oj', '~> 2.12.12'
gem 'oj_mimic_json', '~> 1.0.1'
gem 'pg', '~> 0.18.2'
gem 'postgres_ext', '~> 3.0'
gem 'rails', '4.2.4'
gem 'ransack', '~> 1.7.0'
gem 'react-rails', '~> 1.6'
gem 'rest-client', '~> 1.8'
gem 'roo', '~> 2.2'
gem 'rubytree', '~> 0.9.6'
gem 'sanitize', '~> 4.2'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'seedbank', '~> 0.3'
gem 'simple_form'
gem 'staccato', '~> 0.4.7'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'wicked_pdf', '~> 1.0'
gem 'will_paginate', '~> 3.0.7', require: ['will_paginate', 'will_paginate/active_record']
gem 'will_paginate-bootstrap'
gem 'truncate_html', '~> 0.9.3'
gem 'foundation-rails', '~> 6.2.1'
gem 'order_as_specified', '~> 0.1.0'
gem 'readthis'
gem 'hiredis'
gem 'validate_url', '~> 1.0'
gem 'virtus', '~> 1.0.5'
gem 'ruby-progressbar', '~> 1.7', '>= 1.7.5'
gem 'autoprefixer-rails', '~> 6.3.6'
gem 'rack-proxy', '~> 0.6', require: 'rack/proxy'
gem 'migration_data', '~> 0.2.1'

group :development, :test do
  gem 'byebug'
  gem 'faker'
end

group :development do
  gem 'rack-livereload', '~> 0.3.16'
  gem 'guard-livereload', '~> 2.5', '>= 2.5.2'
  gem 'safe_attributes', '~> 1.0.10'
  gem 'spring'
  gem 'web-console', '~> 2.0'
  gem 'rack-mini-profiler', '~> 0.9.9.2', require: false
  gem 'quiet_assets', '~> 1.1'
  gem 'puma', '~> 3.4'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner', '~> 1.4.1'
  gem 'email_spec', '~> 1.6'
  gem 'guard'
  gem 'guard-minitest'
  gem 'minitest-focus'
  gem 'minitest-rails-capybara'
  gem 'poltergeist'
  gem 'shoulda', require: false
  gem 'webmock', '~> 1.21.0'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-es6-promise', '~> 3.1.2'
  gem 'rails-assets-eventemitter3', '~> 1.2.0'
  gem 'rails-assets-fetch', '~> 0.11.0'
  gem 'rails-assets-lodash', '~> 3.9.3'
  gem 'rails-assets-knockout', '~> 3.3.0'
  gem 'rails-assets-classnames', '~> 2.2.3'
  gem 'rails-assets-selectize', '~> 0.12.1'
end
