branch-defaults:
  devops:
    environment: null
    group_suffix: null
global:
  application_name: unbounded-lcms
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.12.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: learntap
  repository: null
  sc: git
  workspace_type: Application
