branch-defaults:
  devops:
    environment: development
global:
  application_name: unbounded-lcms
  branch: null
  default_ec2_keyname: Main-key
  default_platform: Multi-container Docker 18.03.1-ce (Generic)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: learntap
  repository: null
  sc: git
  workspace_type: Application
